services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flywise-app
    env_file:
      - .env
    environment:
      DB_HOST: inf2006-db.cnepcitijuis.us-east-1.rds.amazonaws.com
      DB_PORT: 3306
      DB_NAME: group_project
      DB_SSL: "true"
    ports:
      - "8000:8000"
    restart: unless-stopped
